insert into ACTIVITY ("NAME") values ('Badminton');
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (266, '_130_', 1);
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (317, '_155_', 1);
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (368, '_180_', 1);
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (419, '_205_', 1);
insert into ACTIVITY ("NAME") values ('Tennis');
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (472, '_130_', 2);
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (563, '_155_', 2);
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (654, '_180_', 2);
insert into CALORIES (AMOUNT, WEIGHTCAT, ACTIVITY_ID) values (745, '_205_', 2);

insert into AUTHUSER (AGE, GENDER, "NAME", PASSWORD, USERNAME, WEIGHTCAT) values (23, 'Male', 'John Lock', 'password', 'John', '_155_');
insert into ACTIVITYRECORD (ACTIVITYDATE, CALORIESBURNT, DURATION, AUTHUSER_ID, CALORIES_ID) VALUES ('2013-10-10', 120, 100, 1, 2);
insert into ACTIVITYRECORD (ACTIVITYDATE, CALORIESBURNT, DURATION, AUTHUSER_ID, CALORIES_ID) VALUES ('2013-11-12', 150, 120, 1, 2);

insert into AUTHUSER (AGE, GENDER, "NAME", PASSWORD, USERNAME, WEIGHTCAT) values (31, 'Female', 'Anna Lucia', 'pwd', 'Anna', '_130_');
insert into ACTIVITYRECORD (ACTIVITYDATE, CALORIESBURNT, DURATION, AUTHUSER_ID, CALORIES_ID) VALUES ('2013-11-10', 92, 60, 2, 5);
